# Generated by Django 3.1.4 on 2020-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
