# Generated by Django 3.1.4 on 2020-12-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
