# Generated by Django 3.1.4 on 2020-12-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descricao',
            new_name='tema',
        ),
    ]
