# Generated by Django 3.1.4 on 2020-12-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20201213_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tema',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
