# Generated by Django 3.1.4 on 2020-12-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_auto_20201213_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nome_post',
            new_name='titulo',
        ),
    ]
