# Generated by Django 3.1.4 on 2020-12-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_auto_20201213_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='corpo',
        ),
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
